version: "3"
services:
  healthcare-db:
    container_name: healthcare-db
    image: postgis/postgis:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=healthcare-db
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  healthcare-be:
    container_name: healthcare-be
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - healthcare-db
    environment:
      - GEOCODE_API_KEY=
      - PORT=8080
      - DB_HOST=healthcare-db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=healthcare-db
      - SSL_MODE=disable
  healthcare-fe:
    container_name: healthcare-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=
