definitions:
  handlers.AddPayload:
    properties:
      numbers:
        items:
          type: number
        type: array
    type: object
  handlers.ComputePayload:
    properties:
      add:
        items:
          type: number
        type: array
      subtract:
        items:
          type: number
        type: array
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.FindSpecialistPayload:
    properties:
      radius:
        type: integer
      specialty_id:
        type: integer
      user_location:
        type: string
    type: object
  handlers.GetAddressFromWKTPayload:
    properties:
      wkt_location:
        type: string
    type: object
  handlers.GetAddressFromWKTResponse:
    properties:
      display_name:
        type: string
    type: object
  handlers.GetCurrentTimeResponse:
    properties:
      time:
        type: string
    type: object
  handlers.GetSpecialtiesResponse:
    properties:
      specialties:
        items:
          $ref: '#/definitions/types.Specialty'
        type: array
    type: object
  handlers.GetWKTLocationPayload:
    properties:
      user_location:
        type: string
    type: object
  handlers.SubtractPayload:
    properties:
      number:
        type: number
      subtract:
        items:
          type: number
        type: array
    type: object
  handlers.SuccessResponse:
    properties:
      result:
        type: number
    type: object
  types.Specialty:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /location/address:
    post:
      consumes:
      - application/json
      description: Get the address based on the WKT location
      operationId: address
      parameters:
      - description: WKT location
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.GetAddressFromWKTPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetAddressFromWKTResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get address from WKT
  /location/wkt:
    post:
      consumes:
      - application/json
      description: Get the WKT location based on the user's location
      operationId: location
      parameters:
      - description: User location
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.GetWKTLocationPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get WKT location
  /math/add:
    post:
      consumes:
      - application/json
      description: Add all numbers provided in the payload
      operationId: add-operation
      parameters:
      - description: Numbers to add
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.AddPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Add numbers
  /math/compute:
    post:
      consumes:
      - application/json
      description: Adds all numbers in the 'add' list and subtracts all numbers in
        the 'subtract' list.
      parameters:
      - description: Compute payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.ComputePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Compute result
      tags:
      - Math Operations
  /math/subtract:
    post:
      consumes:
      - application/json
      description: Subtract all numbers in the 'subtract' list from the 'number'.
      parameters:
      - description: Numbers to substract from the 'number'
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.SubtractPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Subtract numbers
      tags:
      - Math Operations
  /specialist/find:
    post:
      consumes:
      - application/json
      description: Find a specialist based on the user's location, specialty, and
        radius
      operationId: find-specialist
      parameters:
      - description: Specialty, radius, and user location
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.FindSpecialistPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Find specialist
  /specialty/all:
    post:
      consumes:
      - application/json
      description: Get all specialties
      operationId: specialties
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetSpecialtiesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get specialties
  /time/current:
    post:
      consumes:
      - application/json
      description: Get the current time in a specific timezone
      operationId: current-time
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetCurrentTimeResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get current time
swagger: "2.0"
